from __future__ import annotations

from html import escape


DISCLAIMER_TEXT = (
    "This digest is an automated summary of public news for internal awareness. "
    "It is not legal advice, not an official compliance determination, and must be "
    "reviewed by a human before any action."
)

DISCLAIMER_LLM = " Portions of this message were generated by an AI model from fetched headlines only."
DISCLAIMER_FALLBACK = " This message was assembled from fetched headlines without an AI summary."


def disclaimer_text(*, used_llm: bool) -> str:
    extra = DISCLAIMER_LLM if used_llm else DISCLAIMER_FALLBACK
    return DISCLAIMER_TEXT + extra


def attach_disclaimer(html: str, text: str, *, used_llm: bool) -> tuple[str, str]:
    notice = disclaimer_text(used_llm=used_llm)
    html_block = f'<p style="font-size:12px;color:#444">{escape(notice)}</p>'
    return f"{html}\n<hr>\n{html_block}", f"{text}\n\n---\n{notice}"


def recipient_log_label(to_email: str) -> str:
    if "@" not in to_email:
        return "(redacted)"
    _, domain = to_email.rsplit("@", 1)
    return f"*@{domain}"
